// Generated by `npm run gen:api` from the backend OpenAPI schema. Do not edit.

export interface paths {
    "/api/admin/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Businesses */
        get: operations["list_businesses_api_admin_businesses_get"];
        put?: never;
        /** Create Business */
        post: operations["create_business_api_admin_businesses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/businesses/{business_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Member */
        put: operations["upsert_member_api_admin_businesses__business_id__members_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Otp */
        post: operations["request_otp_api_auth_otp_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp */
        post: operations["verify_otp_api_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Select Business */
        put: operations["select_business_api_me_business_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/w/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_w_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/w/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Context */
        get: operations["workspace_context_api_w_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/w/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_w_locations_get"];
        put?: never;
        /** Create Location */
        post: operations["create_location_api_w_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/w/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location */
        get: operations["get_location_api_w_locations__location_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Location */
        patch: operations["update_location_api_w_locations__location_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id: string | null;
            /** Entity Type */
            entity_type: string | null;
            /** Seq */
            seq: number;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
            /** Next Before Seq */
            next_before_seq: number | null;
        };
        /** BusinessCreate */
        BusinessCreate: {
            /** Enabled Modules */
            enabled_modules?: components["schemas"]["ModuleKey"][] | null;
            /** Gstin */
            gstin?: string | null;
            /** Name */
            name: string;
            /** Name Ta */
            name_ta?: string | null;
            /** Vertical Key */
            vertical_key: string;
        };
        /** BusinessOut */
        BusinessOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled Modules */
            enabled_modules: string[];
            /** Gstin */
            gstin: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Name Ta */
            name_ta: string | null;
            /** Status */
            status: string;
            /** Vertical Key */
            vertical_key: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationCreate */
        LocationCreate: {
            /**
             * Kind
             * @default shop
             * @enum {string}
             */
            kind: "shop" | "godown" | "cold_storage" | "other";
            /** Name */
            name: string;
            /** Name Ta */
            name_ta?: string | null;
        };
        /** LocationOut */
        LocationOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "shop" | "godown" | "cold_storage" | "other";
            /** Name */
            name: string;
            /** Name Ta */
            name_ta: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LocationUpdate */
        LocationUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Kind */
            kind?: ("shop" | "godown" | "cold_storage" | "other") | null;
            /** Name */
            name?: string | null;
            /** Name Ta */
            name_ta?: string | null;
        };
        /** MeOut */
        MeOut: {
            /** Current Business Id */
            current_business_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Platform Admin */
            is_platform_admin: boolean;
            /** Language */
            language: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipOut"][];
            /** Name */
            name: string;
            /** Name Ta */
            name_ta: string | null;
        };
        /** MemberIn */
        MemberIn: {
            /** Location Ids */
            location_ids?: string[] | null;
            /** Name */
            name: string;
            /** Name Ta */
            name_ta?: string | null;
            /** Phone */
            phone: string;
            role: components["schemas"]["Role"];
        };
        /** MemberOut */
        MemberOut: {
            /**
             * Business Id
             * Format: uuid
             */
            business_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Location Ids */
            location_ids: string[] | null;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MembershipOut */
        MembershipOut: {
            /**
             * Business Id
             * Format: uuid
             */
            business_id: string;
            /** Business Name */
            business_name: string;
            /** Business Name Ta */
            business_name_ta: string | null;
            role: components["schemas"]["Role"];
        };
        /**
         * ModuleKey
         * @enum {string}
         */
        ModuleKey: "sell" | "stock" | "money" | "buy" | "bills" | "customers" | "suppliers" | "wastage" | "reports" | "staff" | "audit" | "settings";
        /** OtpRequestIn */
        OtpRequestIn: {
            /** Phone */
            phone: string;
        };
        /** OtpRequestOut */
        OtpRequestOut: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** OtpVerifyIn */
        OtpVerifyIn: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "manager" | "billing" | "stock" | "viewer";
        /** SelectBusinessIn */
        SelectBusinessIn: {
            /**
             * Business Id
             * Format: uuid
             */
            business_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkspaceContextOut
         * @description What the workspace UI needs after login: which business, which modules, what this user may do.
         */
        WorkspaceContextOut: {
            business: components["schemas"]["BusinessOut"];
            /** Location Ids */
            location_ids: string[] | null;
            /** Permissions */
            permissions: string[];
            /** Role */
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_businesses_api_admin_businesses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_business_api_admin_businesses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_member_api_admin_businesses__business_id__members_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_otp_api_auth_otp_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_api_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_business_api_me_business_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectBusinessIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_w_audit_events_get: {
        parameters: {
            query?: {
                before_seq?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_context_api_w_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceContextOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_w_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_location_api_w_locations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_location_api_w_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_location_api_w_locations__location_id__patch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                location_id: string;
            };
            cookie?: {
                cc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
