// Regenerates src/api/schema.d.ts from the backend's OpenAPI schema. Never edit that file by hand.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const backend = fileURLToPath(new URL("../../backend", import.meta.url));
// Dumping the schema needs no real services: placeholders satisfy the settings check for this process only.
const placeholders = Object.fromEntries(
  [
    "SESSION_SECRET",
    "R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "R2_BUCKET",
  ].map((k) => [k, "schema-dump-placeholder"]),
);
const env = {
  ...placeholders,
  DATABASE_URL: "postgresql+psycopg://schema:dump@localhost/none",
  DATABASE_URL_DIRECT: "postgresql+psycopg://schema:dump@localhost/none",
  APP_ENV: "development",
  ...process.env,
};

function dump() {
  const args = ["run", "--no-sync", "python", "-m", "app.openapi"];
  try {
    return execFileSync("uv", args, { cwd: backend, env, encoding: "utf8" });
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
    return execFileSync("python", ["-m", "uv", ...args], { cwd: backend, env, encoding: "utf8" });
  }
}

const schema = JSON.parse(dump());
const ast = await openapiTS(schema);
const header = "// Generated by `npm run gen:api` from the backend OpenAPI schema. Do not edit.\n\n";
writeFileSync(new URL("../src/api/schema.d.ts", import.meta.url), header + astToString(ast));
console.log("src/api/schema.d.ts updated");
