"""business setup queue platform users

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 13:26:02.429176
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# businesses is a platform table (no business_id, no RLS): a plain nullable column is enough here.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("businesses", sa.Column("setup_completed_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "setup_completed_at")
    # ### end Alembic commands ###
