"""subscriptions and plans

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-28 20:15:18.620201
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Both new tables are platform tables (no business_id via TenantMixin, no RLS) — same as businesses and
# vertical_templates: the platform team's own data, not a trader's.

DEFAULT_TRIAL_DAYS = 14

# key, name, Tamil name, price in paise (None = "contact us"), billing period, trial days
PLANS: tuple[tuple[str, str, str, int | None, str, int | None], ...] = (
    ("trial", "Free Trial", "இலவச சோதனை", 0, "trial", DEFAULT_TRIAL_DAYS),
    ("basic", "Basic", "அடிப்படை", 99_900, "monthly", None),  # Rs 999/month
    ("pro", "Pro", "புரோ", 249_900, "monthly", None),  # Rs 2,499/month
    ("enterprise", "Enterprise", "நிறுவனம்", None, "yearly", None),  # priced by negotiation
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_plans",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("name_ta", sa.String(length=120), nullable=False),
        sa.Column("price_paise", sa.BigInteger(), nullable=True),
        sa.Column("billing_period", sa.String(length=10), nullable=False),
        sa.Column("trial_days", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "billing_period IN ('trial', 'monthly', 'yearly')", name=op.f("ck_subscription_plans_billing_period")
        ),
        sa.CheckConstraint("price_paise IS NULL OR price_paise >= 0", name=op.f("ck_subscription_plans_price")),
        sa.CheckConstraint("trial_days IS NULL OR trial_days > 0", name=op.f("ck_subscription_plans_trial_days")),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_subscription_plans")),
    )
    op.create_table(
        "subscriptions",
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("plan_key", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("price_paise", sa.BigInteger(), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('trial', 'active', 'past_due', 'cancelled')", name=op.f("ck_subscriptions_status")
        ),
        sa.CheckConstraint("price_paise IS NULL OR price_paise >= 0", name=op.f("ck_subscriptions_price")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_subscriptions_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_key"],
            ["subscription_plans.key"],
            name=op.f("fk_subscriptions_plan_key_subscription_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("business_id", name=op.f("uq_subscriptions_business_id")),
    )
    # ### end Alembic commands ###

    plans = sa.table(
        "subscription_plans",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("name_ta", sa.String),
        sa.column("price_paise", sa.BigInteger),
        sa.column("billing_period", sa.String),
        sa.column("trial_days", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        plans,
        [
            {
                "key": k,
                "name": n,
                "name_ta": ta,
                "price_paise": price,
                "billing_period": period,
                "trial_days": days,
                "is_active": True,
            }
            for k, n, ta, price, period, days in PLANS
        ],
    )
    # backfill: any business created before this migration gets a trial subscription too, so every
    # business has exactly one subscription row from here on (the app assumes this on business.create)
    op.execute(
        f"""
        INSERT INTO subscriptions (id, business_id, plan_key, status, price_paise, trial_ends_at, created_at, updated_at)
        SELECT gen_random_uuid(), b.id, 'trial', 'trial', 0, now() + interval '{DEFAULT_TRIAL_DAYS} days', now(), now()
        FROM businesses b
        LEFT JOIN subscriptions s ON s.business_id = b.id
        WHERE s.id IS NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions")
    op.drop_table("subscription_plans")
    # ### end Alembic commands ###
