"""catalog parties ledgers stock

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 04:01:40.586801
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.config import get_settings

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every table below carries business_id: the app role may only see and write the current business's rows.
TENANT_TABLES = (
    "units",
    "grades",
    "products",
    "varieties",
    "parties",
    "party_ledger_entries",
    "crate_ledger_entries",
    "stock_movements",
    "stock_transfers",
    "wastage_entries",
)
# Ledgers are append-only: UPDATE / DELETE / TRUNCATE are blocked by trigger and revoked from the app role.
APPEND_ONLY_TABLES = (
    "party_ledger_entries",
    "crate_ledger_entries",
    "stock_movements",
    "stock_transfers",
    "wastage_entries",
)


def enable_tenant_rls(table: str) -> None:
    """Same as the helper in 0001 (a migration must not import another one)."""
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {table} "
        "USING (business_id = app_current_business()) WITH CHECK (business_id = app_current_business())"
    )


def make_append_only(table: str, app_role: str) -> None:
    op.execute(
        f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(
        f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
        "FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON {table} FROM {app_role}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grades",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("name_ta", sa.String(length=80), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_grades_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grades")),
        sa.UniqueConstraint("business_id", "name", name=op.f("uq_grades_business_id_name")),
    )
    op.create_index(op.f("ix_grades_business_id"), "grades", ["business_id"], unique=False)
    op.create_table(
        "parties",
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_ta", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=16), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("credit_limit_paise", sa.BigInteger(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('customer', 'supplier')", name=op.f("ck_parties_kind")),
        sa.CheckConstraint(
            "credit_limit_paise IS NULL OR credit_limit_paise >= 0", name=op.f("ck_parties_credit_limit")
        ),
        sa.CheckConstraint("gstin IS NULL OR length(gstin) = 15", name=op.f("ck_parties_gstin_length")),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_parties_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parties")),
        sa.UniqueConstraint("business_id", "id", name=op.f("uq_parties_business_id_id")),
    )
    op.create_index(op.f("ix_parties_business_id"), "parties", ["business_id"], unique=False)
    op.create_index(
        "uq_parties_kind_phone",
        "parties",
        ["business_id", "kind", "phone"],
        unique=True,
        postgresql_where="phone IS NOT NULL",
    )
    op.create_table(
        "units",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("name_ta", sa.String(length=100), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("base_factor", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('weight', 'count')", name=op.f("ck_units_kind")),
        sa.CheckConstraint("base_factor >= 1", name=op.f("ck_units_base_factor")),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_units_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("business_id", "code", name=op.f("uq_units_business_id_code")),
    )
    op.create_index(op.f("ix_units_business_id"), "units", ["business_id"], unique=False)
    op.create_table(
        "crate_ledger_entries",
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("reference_type", sa.String(length=30), nullable=True),
        sa.Column("reference_id", sa.String(length=64), nullable=True),
        sa.Column("reversal_of", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('issued', 'returned', 'adjustment', 'reversal')",
            name=op.f("ck_crate_ledger_entries_entry_type"),
        ),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_crate_ledger_entries_quantity_nonzero")),
        sa.ForeignKeyConstraint(
            ["business_id", "party_id"],
            ["parties.business_id", "parties.id"],
            name=op.f("fk_crate_ledger_entries_business_id_parties"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_crate_ledger_entries_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_crate_ledger_entries_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_crate_ledger_entries_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of"],
            ["crate_ledger_entries.id"],
            name=op.f("fk_crate_ledger_entries_reversal_of_crate_ledger_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crate_ledger_entries")),
        sa.UniqueConstraint("reversal_of", name=op.f("uq_crate_ledger_entries_reversal_of")),
    )
    op.create_index(op.f("ix_crate_ledger_entries_business_id"), "crate_ledger_entries", ["business_id"], unique=False)
    op.create_index(
        "ix_crate_ledger_entries_party", "crate_ledger_entries", ["business_id", "party_id", "id"], unique=False
    )
    op.create_table(
        "party_ledger_entries",
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("reference_type", sa.String(length=30), nullable=True),
        sa.Column("reference_id", sa.String(length=64), nullable=True),
        sa.Column("reversal_of", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('opening', 'sale', 'sale_return', 'purchase', 'purchase_return', 'payment_in', 'payment_out', 'adjustment', 'reversal')",
            name=op.f("ck_party_ledger_entries_entry_type"),
        ),
        sa.CheckConstraint("amount_paise <> 0", name=op.f("ck_party_ledger_entries_amount_nonzero")),
        sa.ForeignKeyConstraint(
            ["business_id", "party_id"],
            ["parties.business_id", "parties.id"],
            name=op.f("fk_party_ledger_entries_business_id_parties"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_party_ledger_entries_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_party_ledger_entries_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of"],
            ["party_ledger_entries.id"],
            name=op.f("fk_party_ledger_entries_reversal_of_party_ledger_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party_ledger_entries")),
        sa.UniqueConstraint("reversal_of", name=op.f("uq_party_ledger_entries_reversal_of")),
    )
    op.create_index(op.f("ix_party_ledger_entries_business_id"), "party_ledger_entries", ["business_id"], unique=False)
    op.create_index(
        "ix_party_ledger_entries_party", "party_ledger_entries", ["business_id", "party_id", "id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_ta", sa.String(length=200), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("default_price_paise", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('weight', 'count')", name=op.f("ck_products_kind")),
        sa.CheckConstraint("default_price_paise IS NULL OR default_price_paise >= 0", name=op.f("ck_products_price")),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_products_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_products_unit_id_units"), ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("business_id", "name", name=op.f("uq_products_business_id_name")),
    )
    op.create_index(op.f("ix_products_business_id"), "products", ["business_id"], unique=False)
    op.create_table(
        "stock_transfers",
        sa.Column("from_location_id", sa.UUID(), nullable=False),
        sa.Column("to_location_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("from_location_id <> to_location_id", name=op.f("ck_stock_transfers_different_locations")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_stock_transfers_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_transfers_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["locations.id"],
            name=op.f("fk_stock_transfers_from_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["locations.id"],
            name=op.f("fk_stock_transfers_to_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
    )
    op.create_index(op.f("ix_stock_transfers_business_id"), "stock_transfers", ["business_id"], unique=False)
    op.create_table(
        "varieties",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("name_ta", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_varieties_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_varieties_product_id_products"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_varieties")),
        sa.UniqueConstraint("business_id", "product_id", "name", name=op.f("uq_varieties_business_id_product_id_name")),
    )
    op.create_index(op.f("ix_varieties_business_id"), "varieties", ["business_id"], unique=False)
    op.create_index(op.f("ix_varieties_product_id"), "varieties", ["product_id"], unique=False)
    op.create_table(
        "stock_movements",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variety_id", sa.UUID(), nullable=True),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("reference_type", sa.String(length=30), nullable=True),
        sa.Column("reference_id", sa.String(length=64), nullable=True),
        sa.Column("reversal_of", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "movement_type IN ('opening', 'adjustment', 'transfer_out', 'transfer_in', 'wastage', 'reversal', 'purchase', 'sale', 'sale_return')",
            name=op.f("ck_stock_movements_movement_type"),
        ),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_stock_movements_quantity_nonzero")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_stock_movements_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_movements_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_stock_movements_grade_id_grades"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_stock_movements_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_stock_movements_product_id_products"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of"],
            ["stock_movements.id"],
            name=op.f("fk_stock_movements_reversal_of_stock_movements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"], ["varieties.id"], name=op.f("fk_stock_movements_variety_id_varieties"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
        sa.UniqueConstraint("reversal_of", name=op.f("uq_stock_movements_reversal_of")),
    )
    op.create_index(op.f("ix_stock_movements_business_id"), "stock_movements", ["business_id"], unique=False)
    op.create_index(
        "ix_stock_movements_item", "stock_movements", ["business_id", "location_id", "product_id"], unique=False
    )
    op.create_table(
        "wastage_entries",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variety_id", sa.UUID(), nullable=True),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("reason_code", sa.String(length=30), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("movement_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "reason_code IN ('rotten', 'damaged', 'shrinkage', 'spoiled_in_transit', 'other')",
            name=op.f("ck_wastage_entries_reason_code"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_wastage_entries_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_wastage_entries_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_wastage_entries_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_wastage_entries_grade_id_grades"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_wastage_entries_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_wastage_entries_movement_id_stock_movements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_wastage_entries_product_id_products"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"], ["varieties.id"], name=op.f("fk_wastage_entries_variety_id_varieties"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wastage_entries")),
    )
    op.create_index(op.f("ix_wastage_entries_business_id"), "wastage_entries", ["business_id"], unique=False)
    # ### end Alembic commands ###

    app_role = get_settings().db_app_role
    for table in TENANT_TABLES:
        enable_tenant_rls(table)
    for table in APPEND_ONLY_TABLES:
        make_append_only(table, app_role)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wastage_entries_business_id"), table_name="wastage_entries")
    op.drop_table("wastage_entries")
    op.drop_index("ix_stock_movements_item", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_business_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_varieties_product_id"), table_name="varieties")
    op.drop_index(op.f("ix_varieties_business_id"), table_name="varieties")
    op.drop_table("varieties")
    op.drop_index(op.f("ix_stock_transfers_business_id"), table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index(op.f("ix_products_business_id"), table_name="products")
    op.drop_table("products")
    op.drop_index("ix_party_ledger_entries_party", table_name="party_ledger_entries")
    op.drop_index(op.f("ix_party_ledger_entries_business_id"), table_name="party_ledger_entries")
    op.drop_table("party_ledger_entries")
    op.drop_index("ix_crate_ledger_entries_party", table_name="crate_ledger_entries")
    op.drop_index(op.f("ix_crate_ledger_entries_business_id"), table_name="crate_ledger_entries")
    op.drop_table("crate_ledger_entries")
    op.drop_index(op.f("ix_units_business_id"), table_name="units")
    op.drop_table("units")
    op.drop_index("uq_parties_kind_phone", table_name="parties", postgresql_where="phone IS NOT NULL")
    op.drop_index(op.f("ix_parties_business_id"), table_name="parties")
    op.drop_table("parties")
    op.drop_index(op.f("ix_grades_business_id"), table_name="grades")
    op.drop_table("grades")
    # ### end Alembic commands ###
