"""sales purchases payments

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 07:28:04.123450
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.config import get_settings

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every new table carries business_id: the app role may only see and write the current business's rows.
TENANT_TABLES = (
    "bill_sequences",
    "bills",
    "bill_lines",
    "sale_returns",
    "sale_return_lines",
    "purchases",
    "purchase_lines",
    "payments",
)
# Never updated or deleted: UPDATE / DELETE / TRUNCATE are blocked by trigger and revoked from the app role.
APPEND_ONLY_TABLES = ("bill_lines", "sale_returns", "sale_return_lines", "purchase_lines", "payments")
# Legal documents: the only change ever allowed is active -> void (with reason, time and user). No delete.
VOIDABLE_TABLES = ("bills", "purchases")


def enable_tenant_rls(table: str) -> None:
    """Same as the helper in 0001 (a migration must not import another one)."""
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {table} "
        "USING (business_id = app_current_business()) WITH CHECK (business_id = app_current_business())"
    )


def make_append_only(table: str, app_role: str) -> None:
    op.execute(
        f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(
        f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
        "FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON {table} FROM {app_role}")


def make_void_only(table: str, app_role: str) -> None:
    op.execute(
        f"CREATE TRIGGER {table}_void_only BEFORE UPDATE OR DELETE ON {table} "
        "FOR EACH ROW EXECUTE FUNCTION guard_void_only()"
    )
    op.execute(
        f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
        "FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(f"REVOKE DELETE, TRUNCATE ON {table} FROM {app_role}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_sequences",
        sa.Column("fy", sa.String(length=5), nullable=False),
        sa.Column("series", sa.String(length=3), nullable=False),
        sa.Column("next_number", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("next_number >= 1", name=op.f("ck_bill_sequences_next_number")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_bill_sequences_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill_sequences")),
        sa.UniqueConstraint("business_id", "fy", "series", name=op.f("uq_bill_sequences_business_id_fy_series")),
    )
    op.create_index(op.f("ix_bill_sequences_business_id"), "bill_sequences", ["business_id"], unique=False)
    op.create_table(
        "bills",
        sa.Column("series", sa.String(length=3), nullable=False),
        sa.Column("fy", sa.String(length=5), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("bill_number", sa.String(length=16), nullable=False),
        sa.Column("doc_type", sa.String(length=20), nullable=False),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=True),
        sa.Column("party_name", sa.String(length=120), nullable=True),
        sa.Column("party_phone", sa.String(length=16), nullable=True),
        sa.Column("party_gstin", sa.String(length=15), nullable=True),
        sa.Column("party_address", sa.String(length=300), nullable=True),
        sa.Column("seller_name", sa.String(length=120), nullable=False),
        sa.Column("seller_gstin", sa.String(length=15), nullable=True),
        sa.Column("seller_address", sa.String(length=300), nullable=True),
        sa.Column("seller_phone", sa.String(length=16), nullable=True),
        sa.Column("place_of_supply", sa.String(length=2), nullable=True),
        sa.Column("supply_type", sa.String(length=5), nullable=False),
        sa.Column("taxable_paise", sa.BigInteger(), nullable=False),
        sa.Column("cgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("sgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("igst_paise", sa.BigInteger(), nullable=False),
        sa.Column("round_off_paise", sa.BigInteger(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("paid_paise", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("void_reason", sa.String(length=300), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "doc_type <> 'tax_invoice' OR seller_gstin IS NOT NULL", name=op.f("ck_bills_tax_invoice_needs_gstin")
        ),
        sa.CheckConstraint("doc_type IN ('tax_invoice', 'bill_of_supply')", name=op.f("ck_bills_doc_type")),
        sa.CheckConstraint(
            "status = 'active' OR (void_reason IS NOT NULL AND voided_at IS NOT NULL)",
            name=op.f("ck_bills_void_details"),
        ),
        sa.CheckConstraint("status IN ('active', 'void')", name=op.f("ck_bills_status")),
        sa.CheckConstraint("supply_type IN ('intra', 'inter')", name=op.f("ck_bills_supply_type")),
        sa.CheckConstraint("mod(total_paise, 100) = 0", name=op.f("ck_bills_whole_rupees")),
        sa.CheckConstraint(
            "total_paise >= 0 AND paid_paise >= 0 AND paid_paise <= total_paise", name=op.f("ck_bills_amounts")
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "party_id"],
            ["parties.business_id", "parties.id"],
            name=op.f("fk_bills_business_id_parties"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_bills_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_bills_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_bills_location_id_locations"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["voided_by"], ["users.id"], name=op.f("fk_bills_voided_by_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills")),
        sa.UniqueConstraint("business_id", "bill_number", name=op.f("uq_bills_business_id_bill_number")),
        sa.UniqueConstraint("business_id", "fy", "series", "seq", name=op.f("uq_bills_business_id_fy_series_seq")),
        sa.UniqueConstraint("business_id", "id", name=op.f("uq_bills_business_id_id")),
    )
    op.create_index(op.f("ix_bills_business_id"), "bills", ["business_id"], unique=False)
    op.create_index("ix_bills_date", "bills", ["business_id", "bill_date", "id"], unique=False)
    op.create_index("ix_bills_party", "bills", ["business_id", "party_id", "id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("party_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("reference_type", sa.String(length=30), nullable=True),
        sa.Column("reference_id", sa.String(length=64), nullable=True),
        sa.Column("reversal_of", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("direction IN ('in', 'out')", name=op.f("ck_payments_direction")),
        sa.CheckConstraint(
            "method IN ('cash', 'upi', 'card', 'bank', 'cheque', 'other')", name=op.f("ck_payments_method")
        ),
        sa.CheckConstraint("amount_paise > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["business_id", "party_id"],
            ["parties.business_id", "parties.id"],
            name=op.f("fk_payments_business_id_parties"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_payments_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_payments_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of"], ["payments.id"], name=op.f("fk_payments_reversal_of_payments"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("reversal_of", name=op.f("uq_payments_reversal_of")),
    )
    op.create_index(op.f("ix_payments_business_id"), "payments", ["business_id"], unique=False)
    op.create_index("ix_payments_party", "payments", ["business_id", "party_id", "id"], unique=False)
    op.create_index(
        "ix_payments_reference", "payments", ["business_id", "reference_type", "reference_id"], unique=False
    )
    op.create_table(
        "purchases",
        sa.Column("series", sa.String(length=3), nullable=False),
        sa.Column("fy", sa.String(length=5), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("purchase_number", sa.String(length=16), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("supplier_name", sa.String(length=120), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("supplier_bill_no", sa.String(length=40), nullable=True),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("paid_paise", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("void_reason", sa.String(length=300), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status = 'active' OR (void_reason IS NOT NULL AND voided_at IS NOT NULL)",
            name=op.f("ck_purchases_void_details"),
        ),
        sa.CheckConstraint("status IN ('active', 'void')", name=op.f("ck_purchases_status")),
        sa.CheckConstraint(
            "total_paise >= 0 AND paid_paise >= 0 AND paid_paise <= total_paise", name=op.f("ck_purchases_amounts")
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "supplier_id"],
            ["parties.business_id", "parties.id"],
            name=op.f("fk_purchases_business_id_parties"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_purchases_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_purchases_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_purchases_location_id_locations"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["voided_by"], ["users.id"], name=op.f("fk_purchases_voided_by_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
        sa.UniqueConstraint("business_id", "fy", "series", "seq", name=op.f("uq_purchases_business_id_fy_series_seq")),
        sa.UniqueConstraint("business_id", "id", name=op.f("uq_purchases_business_id_id")),
        sa.UniqueConstraint("business_id", "purchase_number", name=op.f("uq_purchases_business_id_purchase_number")),
    )
    op.create_index(op.f("ix_purchases_business_id"), "purchases", ["business_id"], unique=False)
    op.create_index("ix_purchases_date", "purchases", ["business_id", "purchase_date", "id"], unique=False)
    op.create_table(
        "sale_returns",
        sa.Column("bill_id", sa.UUID(), nullable=False),
        sa.Column("series", sa.String(length=3), nullable=False),
        sa.Column("fy", sa.String(length=5), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("return_number", sa.String(length=16), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("taxable_paise", sa.BigInteger(), nullable=False),
        sa.Column("cgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("sgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("igst_paise", sa.BigInteger(), nullable=False),
        sa.Column("round_off_paise", sa.BigInteger(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("refund_paise", sa.BigInteger(), nullable=False),
        sa.Column("refund_method", sa.String(length=10), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "total_paise >= 0 AND refund_paise >= 0 AND refund_paise <= total_paise",
            name=op.f("ck_sale_returns_amounts"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "bill_id"],
            ["bills.business_id", "bills.id"],
            name=op.f("fk_sale_returns_business_id_bills"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_sale_returns_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_sale_returns_created_by_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_sale_returns_location_id_locations"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_returns")),
        sa.UniqueConstraint(
            "business_id", "fy", "series", "seq", name=op.f("uq_sale_returns_business_id_fy_series_seq")
        ),
        sa.UniqueConstraint("business_id", "id", name=op.f("uq_sale_returns_business_id_id")),
        sa.UniqueConstraint("business_id", "return_number", name=op.f("uq_sale_returns_business_id_return_number")),
    )
    op.create_index("ix_sale_returns_bill", "sale_returns", ["business_id", "bill_id"], unique=False)
    op.create_index(op.f("ix_sale_returns_business_id"), "sale_returns", ["business_id"], unique=False)
    op.create_table(
        "bill_lines",
        sa.Column("bill_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.SmallInteger(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variety_id", sa.UUID(), nullable=True),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("description_ta", sa.String(length=400), nullable=True),
        sa.Column("hsn_code", sa.String(length=8), nullable=True),
        sa.Column("unit_code", sa.String(length=20), nullable=False),
        sa.Column("unit_base_factor", sa.BigInteger(), nullable=False),
        sa.Column("quantity_base", sa.BigInteger(), nullable=False),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("gst_rate_bp", sa.SmallInteger(), nullable=False),
        sa.Column("taxable_paise", sa.BigInteger(), nullable=False),
        sa.Column("cgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("sgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("igst_paise", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("quantity_base > 0 AND unit_price_paise >= 0", name=op.f("ck_bill_lines_amounts")),
        sa.ForeignKeyConstraint(
            ["business_id", "bill_id"], ["bills.business_id", "bills.id"], name=op.f("fk_bill_lines_business_id_bills")
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_bill_lines_business_id_businesses"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_bill_lines_grade_id_grades"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_bill_lines_product_id_products"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_bill_lines_unit_id_units"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"], ["varieties.id"], name=op.f("fk_bill_lines_variety_id_varieties"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill_lines")),
        sa.UniqueConstraint("bill_id", "line_no", name=op.f("uq_bill_lines_bill_id_line_no")),
        sa.UniqueConstraint("business_id", "id", name=op.f("uq_bill_lines_business_id_id")),
    )
    op.create_index(op.f("ix_bill_lines_business_id"), "bill_lines", ["business_id"], unique=False)
    op.create_table(
        "purchase_lines",
        sa.Column("purchase_id", sa.UUID(), nullable=False),
        sa.Column("line_no", sa.SmallInteger(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variety_id", sa.UUID(), nullable=True),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("description_ta", sa.String(length=400), nullable=True),
        sa.Column("unit_code", sa.String(length=20), nullable=False),
        sa.Column("unit_base_factor", sa.BigInteger(), nullable=False),
        sa.Column("quantity_base", sa.BigInteger(), nullable=False),
        sa.Column("unit_cost_paise", sa.BigInteger(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "quantity_base > 0 AND unit_cost_paise >= 0 AND amount_paise >= 0", name=op.f("ck_purchase_lines_amounts")
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "purchase_id"],
            ["purchases.business_id", "purchases.id"],
            name=op.f("fk_purchase_lines_business_id_purchases"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_purchase_lines_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_purchase_lines_grade_id_grades"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_purchase_lines_product_id_products"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_purchase_lines_unit_id_units"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"], ["varieties.id"], name=op.f("fk_purchase_lines_variety_id_varieties"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_lines")),
        sa.UniqueConstraint("purchase_id", "line_no", name=op.f("uq_purchase_lines_purchase_id_line_no")),
    )
    op.create_index(op.f("ix_purchase_lines_business_id"), "purchase_lines", ["business_id"], unique=False)
    op.create_table(
        "sale_return_lines",
        sa.Column("return_id", sa.UUID(), nullable=False),
        sa.Column("bill_line_id", sa.UUID(), nullable=False),
        sa.Column("quantity_base", sa.BigInteger(), nullable=False),
        sa.Column("taxable_paise", sa.BigInteger(), nullable=False),
        sa.Column("cgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("sgst_paise", sa.BigInteger(), nullable=False),
        sa.Column("igst_paise", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("quantity_base > 0", name=op.f("ck_sale_return_lines_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["business_id", "bill_line_id"],
            ["bill_lines.business_id", "bill_lines.id"],
            name=op.f("fk_sale_return_lines_business_id_bill_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "return_id"],
            ["sale_returns.business_id", "sale_returns.id"],
            name=op.f("fk_sale_return_lines_business_id_sale_returns"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_sale_return_lines_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_return_lines")),
    )
    op.create_index(
        "ix_sale_return_lines_bill_line", "sale_return_lines", ["business_id", "bill_line_id"], unique=False
    )
    op.create_index(op.f("ix_sale_return_lines_business_id"), "sale_return_lines", ["business_id"], unique=False)
    op.add_column("businesses", sa.Column("address", sa.String(length=300), nullable=True))
    op.add_column("businesses", sa.Column("phone", sa.String(length=16), nullable=True))
    op.add_column("products", sa.Column("gst_rate_bp", sa.SmallInteger(), server_default="0", nullable=False))
    op.add_column("products", sa.Column("hsn_code", sa.String(length=8), nullable=True))
    # ### end Alembic commands ###

    app_role = get_settings().db_app_role
    op.execute(
        "CREATE FUNCTION guard_void_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN "
        "IF TG_OP = 'DELETE' THEN "
        "RAISE EXCEPTION '% cannot be deleted', TG_TABLE_NAME USING ERRCODE = 'insufficient_privilege'; END IF; "
        "IF OLD.status = 'void' THEN "
        "RAISE EXCEPTION 'a cancelled % cannot be changed', TG_TABLE_NAME USING ERRCODE = 'insufficient_privilege'; END IF; "
        "IF NEW.status <> 'void' OR (to_jsonb(NEW) - 'status' - 'void_reason' - 'voided_at' - 'voided_by') "
        "IS DISTINCT FROM (to_jsonb(OLD) - 'status' - 'void_reason' - 'voided_at' - 'voided_by') THEN "
        "RAISE EXCEPTION 'a % can only be cancelled, not edited', TG_TABLE_NAME "
        "USING ERRCODE = 'insufficient_privilege'; END IF; "
        "RETURN NEW; END $$"
    )
    for table in TENANT_TABLES:
        enable_tenant_rls(table)
    for table in APPEND_ONLY_TABLES:
        make_append_only(table, app_role)
    for table in VOIDABLE_TABLES:
        make_void_only(table, app_role)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "hsn_code")
    op.drop_column("products", "gst_rate_bp")
    op.drop_column("businesses", "phone")
    op.drop_column("businesses", "address")
    op.drop_index(op.f("ix_sale_return_lines_business_id"), table_name="sale_return_lines")
    op.drop_index("ix_sale_return_lines_bill_line", table_name="sale_return_lines")
    op.drop_table("sale_return_lines")
    op.drop_index(op.f("ix_purchase_lines_business_id"), table_name="purchase_lines")
    op.drop_table("purchase_lines")
    op.drop_index(op.f("ix_bill_lines_business_id"), table_name="bill_lines")
    op.drop_table("bill_lines")
    op.drop_index(op.f("ix_sale_returns_business_id"), table_name="sale_returns")
    op.drop_index("ix_sale_returns_bill", table_name="sale_returns")
    op.drop_table("sale_returns")
    op.drop_index("ix_purchases_date", table_name="purchases")
    op.drop_index(op.f("ix_purchases_business_id"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index("ix_payments_reference", table_name="payments")
    op.drop_index("ix_payments_party", table_name="payments")
    op.drop_index(op.f("ix_payments_business_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_bills_party", table_name="bills")
    op.drop_index("ix_bills_date", table_name="bills")
    op.drop_index(op.f("ix_bills_business_id"), table_name="bills")
    op.drop_table("bills")
    op.drop_index(op.f("ix_bill_sequences_business_id"), table_name="bill_sequences")
    op.drop_table("bill_sequences")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS guard_void_only()")
