"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 14:14:51.968671
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.core.config import get_settings

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables carrying business_id that the app role may only see for the current business.
TENANT_TABLES = ("locations", "idempotency_keys")
# frozen copy: a migration must not change when app code does
ALL_MODULES = [
    "sell",
    "stock",
    "money",
    "buy",
    "bills",
    "customers",
    "suppliers",
    "wastage",
    "reports",
    "staff",
    "audit",
    "settings",
]


def enable_tenant_rls(table: str) -> None:
    """Copy into later migrations for every new tenant table."""
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")  # applies to the table owner too
    op.execute(
        f"CREATE POLICY tenant_isolation ON {table} "
        "USING (business_id = app_current_business()) WITH CHECK (business_id = app_current_business())"
    )


def make_append_only(table: str, app_role: str) -> None:
    op.execute(
        f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
        "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(
        f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
        "FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON {table} FROM {app_role}")


def _security(app_role: str) -> None:
    # The API's role. Created without LOGIN; ops enable it once with a password (see docs/deployment.md).
    op.execute(
        f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{app_role}') "
        f"THEN CREATE ROLE {app_role} NOLOGIN; END IF; END $$"
    )
    op.execute(f"GRANT USAGE ON SCHEMA public TO {app_role}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {app_role}")
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {app_role}")
    op.execute(f"REVOKE ALL ON alembic_version FROM {app_role}")
    # tables created by later migrations get the same grants automatically
    op.execute(
        f"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {app_role}"
    )
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO {app_role}")

    op.execute(
        "CREATE FUNCTION app_current_business() RETURNS uuid LANGUAGE sql STABLE AS "
        "$$ SELECT NULLIF(current_setting('app.business_id', true), '')::uuid $$"
    )
    op.execute(
        "CREATE FUNCTION forbid_mutation() RETURNS trigger LANGUAGE plpgsql AS "
        "$$ BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME "
        "USING ERRCODE = 'insufficient_privilege'; END $$"
    )
    for table in TENANT_TABLES:
        enable_tenant_rls(table)

    # audit_events: platform events (a login before a business is chosen) have no business_id
    op.execute("ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_events FORCE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY audit_read ON audit_events FOR SELECT USING (business_id = app_current_business())")
    op.execute(
        "CREATE POLICY audit_insert ON audit_events FOR INSERT "
        "WITH CHECK (business_id IS NULL OR business_id = app_current_business())"
    )
    make_append_only("audit_events", app_role)


def _seed_verticals() -> None:
    templates = sa.table(
        "vertical_templates",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("name_ta", sa.String),
        sa.column("default_modules", postgresql.JSONB),
        sa.column("settings", postgresql.JSONB),
    )
    rows = [
        ("banana", "Banana", "வாழைப்பழம்"),
        ("vegetable", "Vegetables", "காய்கறி"),
        ("flower", "Flowers", "பூ"),
        ("tomato", "Tomato", "தக்காளி"),
    ]
    op.bulk_insert(
        templates,
        [{"key": k, "name": n, "name_ta": ta, "default_modules": ALL_MODULES, "settings": {}} for k, n, ta in rows],
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp_challenges",
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_challenges")),
    )
    op.create_index("ix_otp_challenges_ip_created", "otp_challenges", ["ip_hash", "created_at"], unique=False)
    op.create_index("ix_otp_challenges_phone_created", "otp_challenges", ["phone", "created_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_ta", sa.String(length=200), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("language IN ('en', 'ta')", name=op.f("ck_users_language")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_table(
        "vertical_templates",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("name_ta", sa.String(length=120), nullable=False),
        sa.Column("default_modules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_vertical_templates")),
    )
    op.create_table(
        "businesses",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_ta", sa.String(length=200), nullable=True),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("vertical_key", sa.String(length=40), nullable=False),
        sa.Column("enabled_modules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('active', 'suspended')", name=op.f("ck_businesses_status")),
        sa.CheckConstraint("gstin IS NULL OR length(gstin) = 15", name=op.f("ck_businesses_gstin_length")),
        sa.ForeignKeyConstraint(
            ["vertical_key"],
            ["vertical_templates.key"],
            name=op.f("fk_businesses_vertical_key_vertical_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_audit_events_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("seq", name=op.f("uq_audit_events_seq")),
    )
    op.create_index("ix_audit_events_business_seq", "audit_events", ["business_id", "seq"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.SmallInteger(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_idempotency_keys_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_idempotency_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("business_id", "user_id", "key", name=op.f("uq_idempotency_keys_business_id_user_id_key")),
    )
    op.create_index(op.f("ix_idempotency_keys_business_id"), "idempotency_keys", ["business_id"], unique=False)
    op.create_index("ix_idempotency_keys_created_at", "idempotency_keys", ["created_at"], unique=False)
    op.create_table(
        "locations",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("name_ta", sa.String(length=120), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('shop', 'godown', 'cold_storage', 'other')", name=op.f("ck_locations_kind")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_locations_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("business_id", "name", name=op.f("uq_locations_business_id_name")),
    )
    op.create_index(op.f("ix_locations_business_id"), "locations", ["business_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("location_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_memberships_business_id_businesses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("user_id", "business_id", name=op.f("uq_memberships_user_id_business_id")),
    )
    op.create_index(op.f("ix_memberships_business_id"), "memberships", ["business_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_user_sessions_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index(op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###

    _security(get_settings().db_app_role)
    _seed_verticals()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_business_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_locations_business_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index("ix_idempotency_keys_created_at", table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_business_id"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_audit_events_business_seq", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("businesses")
    op.drop_table("vertical_templates")
    op.drop_table("users")
    op.drop_index("ix_otp_challenges_phone_created", table_name="otp_challenges")
    op.drop_index("ix_otp_challenges_ip_created", table_name="otp_challenges")
    op.drop_table("otp_challenges")
    # ### end Alembic commands ###
    app_role = get_settings().db_app_role
    op.execute("DROP FUNCTION IF EXISTS forbid_mutation()")
    op.execute("DROP FUNCTION IF EXISTS app_current_business()")
    op.execute(
        f"ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM {app_role}"
    )
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM {app_role}")
